version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aptxhub-sqlserver
    environment:
      SA_PASSWORD: "Susu@1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - aptxhub-network
    volumes:
      - mssql_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aptxhub-app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Database=APTXHubDb;User=sa;Password=Susu@1234;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - aptxhub-network

networks:
  aptxhub-network:

volumes:
  mssql_data:
